version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=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
    volumes:
      - ./uploads:/app/uploads
      - ./chunks:/app/chunks
    depends_on:
      - worker

  worker:
    build: ./worker
    environment:
      - OPENAI_API_KEY=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
    volumes:
      - ./uploads:/app/worker_uploads
      - ./chunks:/app/chunks
    deploy:
      mode: replicated
      replicas: 4  # parallel workers for speed

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
