version: "3.9"

services:
  api:
    build: ./api
    container_name: app_api
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=mongodb://mongo:27017/loomia
    volumes:
      - ./uploads:/app/uploads
      - ./chunks:/app/chunks
    depends_on:
      - mongo
    restart: unless-stopped

  worker1:
    build: ./worker
    container_name: worker1
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  worker2:
    build: ./worker
    container_name: worker2
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  worker3:
    build: ./worker
    container_name: worker3
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    command: ["mongod", "--quiet"]
    volumes:
      - ./mongo_data:/data/db
    ports:
      - "27018:27017"
