version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ./uploads:/app/uploads
      - ./chunks:/app/chunks
    depends_on:
      - worker
      - mongo

  worker:
    build: ./worker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    deploy:
      mode: replicated
      replicas: 8

  mongo:
    image: mongo
    restart: always
    command: ["mongod", "--quiet"]
    ports:
      - "27017:27017"
