version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=
    volumes:
      - ./uploads:/app/uploads
      - ./chunks:/app/chunks
    depends_on:
      - worker

  worker:
    build: ./worker
    environment:
      - OPENAI_API_KEY=
    volumes:
      - ./uploads:/app/worker_uploads
      - ./chunks:/app/chunks
    deploy:
      mode: replicated
      replicas: 4  # parallel workers for speed

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
